[tool.poetry]
name = "bubblegum"
version = "0.1.0"
description = ""
authors = ["Per Carlsen <per.carlsen@oda.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
polars = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
